version: "3.8"

services:
  api:
    container_name: cm-api
    image: node:20.10.0-alpine
    working_dir: /app
    command: sh -c "yarn install && yarn start:dev"
    environment:
      - NODE_ENV=development
      - MODE=api
    ports:
      - 3000:3000
    volumes:
      - .:/app

  worker:
    container_name: cm-worker
    image: node:20.10.0-alpine
    working_dir: /app
    command: yarn start:dev
    environment:
      - NODE_ENV=development
      - MODE=worker
    ports:
      - 3001:3000
    volumes:
      - .:/app

  mongo:
    container_name: cm-mongo
    image: mongo:7.0.4
    ports:
      - 27017:27017
    volumes:
      - cm.mongo.config:/data/configdb
      - cm.mongo.db:/data/db

  redis:
    container_name: cm-redis
    image: redis:7.2.3-alpine
    ports:
      - 6379:6379

  elasticsearch:
    container_name: cm-elasticsearch
    image: elasticsearch:7.17.20
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    container_name: cm-kibana
    image: kibana:7.17.20
    ports:
      - 5601:5601

volumes:
  cm.mongo.config:
    driver: local
  cm.mongo.db:
    driver: local
